### ISSUE TITLE
Weirdness with sphinx docs

### ISSUE THREAD

**Issue by ksaur** [microsoft/hummingbird#344]
It seems that sphinx doc generation in HB works with torch==1.5 but not 1.6.

Several of the files (ex: `onnx_converter.py`, `iforest.py` get an error such as:

```
134Handler <function doctree_read at 0x7f6aa2c89d40> for event 'doctree-read' threw an exception (exception: type object 'Cast' has no attribute 'training')
```

There are mentions around the `torch` forums on `has no attribute 'training`.    Ex: [this torch sample](https://github.com/blue-season/pywarm/issues/3).  In general, this error message seems nonsensical, as many of the errors occur in python files that do not involve torch.

Further investigation needed.  

For now, using torch==1.5 in the pipeline run for doc gen.

**Comment by interesaaat** [comment]
@ksaur I think this was fixed, right? Can I close it?

**Comment by ksaur** [comment]
Ah! yes, closing!
